out:main.o sum.o mul.o sub.o
	cc main.o sum.o mul.o sub.o -o out
sum.o:sum.c
	cc -c sum.c -o sum.o
sub.o:sub.c
	cc -c sub.c -o sub.o
mul.o:mul.c
	cc -c mul.c -o mul.o
main.o:main.c
	cc -c main.c -o main.o
